apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-preserve-service
spec:
  selector:
    matchLabels:
      app: ts-preserve-service
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-preserve-service
    spec:
      volumes:
        - name: skywalking-agent
          emptyDir: {}
        - name: logback-config-volume
          configMap:
            name: logback-config
      initContainers:
        - name: agent-container
          image: apache/skywalking-java-agent:8.8.0-alpine
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      containers:
        - name: ts-preserve-service
          image: kvelusamycs/ts-preserve-service:1.0.2
          imagePullPolicy: Always
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking
            - name : logback-config-volume
              mountPath: /config
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking:11800"
            - name: SW_GRPC_LOG_SERVER_HOST
              value: "skywalking"
            - name: SW_GRPC_LOG_SERVER_PORT
              value: "11800"
            - name: SW_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/skywalking/agent/skywalking-agent.jar -Dlogging.config=/config/logback.xml -Xmx1G"
          envFrom:
            - configMapRef:
                name: nacos
            - configMapRef:
                name: rabbitmq
          ports:
            - containerPort: 14568
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          readinessProbe:
            tcpSocket:
              port: 14568
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5